[2022-08-12 11:04:21,412] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.extract_sheets manual__2022-08-12T11:03:58.044044+00:00 [queued]>
[2022-08-12 11:04:21,439] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.extract_sheets manual__2022-08-12T11:03:58.044044+00:00 [queued]>
[2022-08-12 11:04:21,440] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:04:21,441] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 11:04:21,442] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:04:21,465] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_sheets> on 2022-08-12 11:03:58.044044+00:00
[2022-08-12 11:04:21,472] {standard_task_runner.py:52} INFO - Started process 212 to run task
[2022-08-12 11:04:21,476] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'extract_sheets', 'manual__2022-08-12T11:03:58.044044+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp_fwxwp2l', '--error-file', '/tmp/tmp2g1h9_tj']
[2022-08-12 11:04:21,478] {standard_task_runner.py:80} INFO - Job 127: Subtask extract_sheets
[2022-08-12 11:04:21,569] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.extract_sheets manual__2022-08-12T11:03:58.044044+00:00 [running]> on host a471224fadbb
[2022-08-12 11:04:21,671] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=extract_sheets
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T11:03:58.044044+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T11:03:58.044044+00:00
[2022-08-12 11:04:21,673] {ETL_Raizen.py:78} INFO - Extracting sheet DPCache_m3
[2022-08-12 11:04:22,028] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_Raizen.py", line 80, in extract_sheets
    get_specific_sheets(wb, wb.sheetnames, i)
AttributeError: 'ExcelFile' object has no attribute 'sheetnames'
[2022-08-12 11:04:22,049] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ETL_Raízen, task_id=extract_sheets, execution_date=20220812T110358, start_date=20220812T110421, end_date=20220812T110422
[2022-08-12 11:04:22,076] {standard_task_runner.py:97} ERROR - Failed to execute job 127 for task extract_sheets ('ExcelFile' object has no attribute 'sheetnames'; 212)
[2022-08-12 11:04:22,131] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-12 11:04:22,211] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
