[2022-08-13 12:08:29,475] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.read_transform_and_save manual__2022-08-13T12:08:15.328303+00:00 [queued]>
[2022-08-13 12:08:29,490] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.read_transform_and_save manual__2022-08-13T12:08:15.328303+00:00 [queued]>
[2022-08-13 12:08:29,491] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-13 12:08:29,491] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-13 12:08:29,492] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-13 12:08:29,509] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): read_transform_and_save> on 2022-08-13 12:08:15.328303+00:00
[2022-08-13 12:08:29,516] {standard_task_runner.py:52} INFO - Started process 3210 to run task
[2022-08-13 12:08:29,520] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'read_transform_and_save', 'manual__2022-08-13T12:08:15.328303+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmprvy_2oy8', '--error-file', '/tmp/tmpm31waich']
[2022-08-13 12:08:29,522] {standard_task_runner.py:80} INFO - Job 337: Subtask read_transform_and_save
[2022-08-13 12:08:29,591] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.read_transform_and_save manual__2022-08-13T12:08:15.328303+00:00 [running]> on host 4bbb34367c41
[2022-08-13 12:08:29,674] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=read_transform_and_save
AIRFLOW_CTX_EXECUTION_DATE=2022-08-13T12:08:15.328303+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-13T12:08:15.328303+00:00
[2022-08-13 12:08:29,676] {ETL_Raizen.py:57} INFO - Processing data of sheet DPCache_m3
[2022-08-13 12:08:32,058] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_Raizen.py", line 65, in read_transform_and_save
    df["unit"] = df["COMBUSTÍVEL"].str.split(" (").str[-1].str.split(")").str[0]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 116, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 789, in split
    result = self._data.array._str_split(pat, n, expand)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/object_array.py", line 320, in _str_split
    regex = re.compile(pat)
  File "/usr/local/lib/python3.7/re.py", line 236, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.7/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/local/lib/python3.7/sre_parse.py", line 813, in _parse
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 1
[2022-08-13 12:08:32,082] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ETL_Raízen, task_id=read_transform_and_save, execution_date=20220813T120815, start_date=20220813T120829, end_date=20220813T120832
[2022-08-13 12:08:32,099] {standard_task_runner.py:97} ERROR - Failed to execute job 337 for task read_transform_and_save (missing ), unterminated subpattern at position 1; 3210)
[2022-08-13 12:08:32,117] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-13 12:08:32,176] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
