[2022-08-13 11:34:17,720] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.create_database_from_parquet manual__2022-08-13T11:33:32.469419+00:00 [queued]>
[2022-08-13 11:34:17,738] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.create_database_from_parquet manual__2022-08-13T11:33:32.469419+00:00 [queued]>
[2022-08-13 11:34:17,738] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-13 11:34:17,739] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-13 11:34:17,740] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-13 11:34:17,764] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_database_from_parquet> on 2022-08-13 11:33:32.469419+00:00
[2022-08-13 11:34:17,770] {standard_task_runner.py:52} INFO - Started process 1056 to run task
[2022-08-13 11:34:17,774] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'create_database_from_parquet', 'manual__2022-08-13T11:33:32.469419+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpysthmebn', '--error-file', '/tmp/tmp47df8lo2']
[2022-08-13 11:34:17,776] {standard_task_runner.py:80} INFO - Job 313: Subtask create_database_from_parquet
[2022-08-13 11:34:17,910] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.create_database_from_parquet manual__2022-08-13T11:33:32.469419+00:00 [running]> on host 4bbb34367c41
[2022-08-13 11:34:18,095] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=create_database_from_parquet
AIRFLOW_CTX_EXECUTION_DATE=2022-08-13T11:33:32.469419+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-13T11:33:32.469419+00:00
[2022-08-13 11:34:18,096] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_Raizen.py", line 115, in create_database_from_parquet
    logging.info(f"Creating database to insert data into tables {sheets[0]} and {sheets[1]}")
KeyError: 0
[2022-08-13 11:34:18,116] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ETL_Raízen, task_id=create_database_from_parquet, execution_date=20220813T113332, start_date=20220813T113417, end_date=20220813T113418
[2022-08-13 11:34:18,135] {standard_task_runner.py:97} ERROR - Failed to execute job 313 for task create_database_from_parquet (0; 1056)
[2022-08-13 11:34:18,189] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-13 11:34:18,289] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
